version: "3"

services:
  samba:
    image: dperson/samba:rpi
    container_name: samba
    command: '-u "pi;${PASSWORD}" -s "server;/server;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=${TZ}
    ports:
      - 139:130
      - 445:445
    volumes: 
      - ${DEFAULT_PATH}:/server/
    restart: always

  rpi-monitor:
    image: michaelmiklis/rpi-monitor:latest
    container_name: rpi-monitor
    environment:
      - TZ=${TZ}
    volumes:
      - /opt/vc:/opt/vc
      - /boot:/boot
      - /sys:/dockerhost/sys:ro
      - /etc:/dockerhost/etc:ro
      - /proc:/dockerhost/proc:ro
      - /usr/lib:/dockerhost/usr/lib:ro
    ports:
      - 8888:8888
    devices:
      - /dev/vchiq
      - /dev/vcsm
    restart: always

# plex-flexget-transmission
  plex:
    image: jaymoulin/plex:1.16.5
    container_name: plex
    expose:
      - 32400
      - 33400
    network_mode: host
    volumes:
      - ${PATH}/Media:/media
      - ${CONFIG_PATH}/plex/tmp:/tmp
      - ${CONFIG_PATH}/plex/Plex Media Server:/root/Library/Application Support/Plex Media Server
    restart: unless-stopped


  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ} 
      - TRANSMISSION_WEB_HOME=/transmission-web-control/ #optional
      - USER=${USER} #optional
      - PASS=${PASSWORD} #optional
    volumes:
      - ${CONFIG_PATH}/transmission/config:/config
      - ${CONFIG_PATH}/transmission/torrents:/downloads
      - ${CONFIG_PATH}/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  flexget:
    build: flexget-arm # https://github.com/pablokbs/plex-rpi/tree/master/flexget-arm
    container_name: flexget
    volumes:
      - ${CONFIG_PATH}/flexget/config:/config
      - ${CONFIG_PATH}/transmission/torrents:/downloads
      - ${PATH}/Media:/storage
    ports:
      - 5050:5050
    environment:
      - ${TZ} 
      - TORRENT_PLUGIN=transmission
      - FG_WEBUI_PASSWD=${PASSWORD}
      - WEB_PASSWD=${PASSWORD}
    restart: unless-stopped
    links:
      - transmission
